name: Deploy Web App (Dev)

on:
  push:
    branches:
      - dev
    paths:
      - 'apps/web/**'
      - 'packages/app/**'
      - 'packages/shared/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Deploy Web App (Dev)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          VITE_BACKEND_URL: https://api.dev.logtheway.com
        run: pnpm --filter web deploy:dev
